### ISSUE TITLE
ujson can be removed now

### ISSUE THREAD

**Issue by newgene** [rjawesome/FoodData_parser#3]
@rjawesome A minor thing I just noticed:

https://github.com/rjawesome/FoodData_parser/blob/c4e89890335924107d32b743be9cd45e8f86d2fb/manifest.json#L18

since you are now using orjson, you can remove this require line from manifest (or change it to `orjson`).

This hub doesn't need to install `ujson` which is not used. `orjson` is part of `biothings` dependencies, so it's always available.

**Comment by rjawesome** [comment]
Fixed in the referenced commit.
